made login occur on new page instead of in pop up
ZachLamb/react-color pull request #20
Opened 2016-10-20 18:36 UTC by ameletyan

2016-10-20 20:52 UTC, sperry94 requested changes
commented lines should be deleted and the user needs to be added to the users ref if they are new users

2016-10-20 20:52 UTC, sperry94 commented on src/util/login.js
> +	// POP UP
commented lines should be deleted

2016-10-20 20:52 UTC, sperry94 commented on src/util/login.js
> +			// ...
need to add the user to the users ref if they aren't there already

2016-10-27 05:01 UTC, calebhsu commented
@ameletyan 
Is this still relevant or can we close this PR?

2016-10-27 17:26 UTC, closed without merging