Id 131687679
ZachLamb/react-color pull request #5
Opened 2016-10-10 04:25 UTC by ZachLamb

@calebhsu , @IanChar, and @seanhansberry. You can now change the size of the matrix within the data.jsx file ,and ID's will be issued to all cells in this syntax: R#C#

2016-10-10 17:47 UTC, calebhsu requested changes
One major thing (that I realize weren't specified on your Pivotal card, sorry).

Peizhe requested that we get remove row.jsx, so the full implementation should happen in matrix.jsx (guessing nested loops).

Keep it 12 x 12 for simplicity's sake for now -- I do like now easy it will be to modify that grid.
Otherwise, looks good!

2016-10-10 17:55 UTC, ZachLamb commented
@calebhsu , got it. That's actually a lot easier. I'll try to work on it right before class, tonight!

2016-10-11 00:15 UTC, ZachLamb commented
@calebhsu , Check it now

2016-10-11 02:06 UTC, calebhsu approved these changes

2016-10-11 02:07 UTC, merged